"""Initial migration

Revision ID: 00b82fbee683
Revises: 
Create Date: 2022-11-26 22:41:06.654052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b82fbee683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_name', sa.String(length=50), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_tax_number', sa.Integer(), nullable=True),
    sa.Column('entity_accountant', sa.Integer(), nullable=True),
    sa.Column('insertion_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_accountant'], ['accountant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_entity')
    op.drop_table('accountant')
    # ### end Alembic commands ###
